#!/bin/env python

"""
$ report-new-linter-errors snapshot|exec <command> [args...]
"""

import subprocess
import sys

def main(argv: list[str]):
    command = argv[1]
    if command == 'snapshot':
        snapshot = subprocess.run(argv[2:], stdout=subprocess.PIPE)
        with open('snapshot', 'wb') as f:
            f.write(snapshot.stdout)
    elif command == 'exec':
        with open('snapshot', 'rb') as f:
            snapshot = f.read()
        new_snapshot = subprocess.run(argv[2:], stdout=subprocess.PIPE)
        with open('new_snapshot', 'wb') as f:
            f.write(new_snapshot.stdout)
        diff = subprocess.run(['diff', '-u', '-', 'new_snapshot'], input=snapshot, stdout=subprocess.PIPE)
        print(diff.stdout.decode())
    else:
        print(f'Invalid command {repr(command)}')
        sys.exit(1)

if __name__ == '__main__':
    main(sys.argv)